name: Replicate Repos

on:
  push:
    branches:
      - main

jobs:
  replicate_repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory:  ${{ github.workspace }}

    - name: Replicate Repos
      run: python replicate_repos.py
      env:
        ADO_ORG_URL: ${{ secrets.ADO_ORG_URL }}
        ADO_PAT: ${{ secrets.ADO_PAT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        REPOS_TO_REPLICATE: repo1 
      working-directory:  ${{ github.workspace }}